#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#端口设置
server:
  port: 8084
